### ISSUE TITLE
[Add new CEFI resource]: polar data access and visualization 

### ISSUE THREAD

**Issue by shospital** [NOAA-CEFI-Portal/CEFI-info-hub-list#123]
### What is the best title for the data/resource?

Arctic and Antarctic Ocean Satellite Data Portal

### What is URL that links to data/resource?

https://polarwatch.noaa.gov/

### Contact Details

sun.bak-hospital@noaa.gov

### Tell us a bit about the data/resource!

PolarWatch, part of the NOAA CoastWatch program, provides access to download and visualize satellite observation data for high latitude regions, specifically the Arctic and Southern Oceans.

### Provide a representative figure that relates to the data/resource!

![Screenshot 2024-06-14 at 1 26 49 PM](https://github.com/NOAA-CEFI-Portal/CEFI-info-hub-list/assets/119896595/efe563f8-db7f-499f-a062-828c8b8a1320)

### Dataset

0-Any, 8-ARGO Floats

### Time Scale

0-Any, 2-Daily, 4-Weekly, 5-Monthly

### Variables

1-Sea Surface Temperature (SST), 2-Sea Level Height, 6-Salinity, 9-Chlorphyll, 13-Sea-Ice, 28-Phytoplankton, 41-Chemical Variables

### Product Types

4-Gridded Analysis, 9-In-situ, 10-Remote Sensing, 11-Data Guides/Repositories, 12-Code Repository, 15-Educational, 17-Analysis Tools, 18-ERDDAP Installations

### Topics

10-Arctic, 21-Algae Blooms

### Observing Platforms

3-Ship, 4-Airplane, 5-Satellite, 6-Floats, 10-Gliders

### Regions

2-Pacific Ocean, 4-Arctic Ocean, 5-Bering Sea, 15-Global, 17-Alaska, 18-US: West Coast

### Organizations

5-NOAA NESDIS, 14-NOAA Fisheries

**Comment by shospital** [comment]
@chiaweh2 thank you.  I uploaded two images so that you or your group can choose that works best for your portal.  Please feel free to choose one or crop to fit to your needs.  Thank you.
-Sunny

**Comment by chiaweh2** [comment]
BTW love the tutorial and all the related material. The data portal is also intuitive and easy to use. Love it!

**Comment by chiaweh2** [comment]
To keep in archive ![Screenshot 2024-06-14 at 1 26 37 PM](https://github.com/NOAA-CEFI-Portal/CEFI-info-hub-list/assets/119896595/3dbf6bcc-072c-47cd-9b4a-f09bebfb3427)

**Comment by shospital** [comment]
Thank you! I thought yours was very well organized and done as well.  I hope we can collaborate more in the future.

**Comment by shospital** [comment]
> @shospital I change the title to "Arctic and Antarctic Ocean Satellite Data Portal" Does this sounds good to you?

Yes! thank you

**Comment by chiaweh2** [comment]
> Thank you! I thought yours was very well organized and done as well. I hope we can collaborate more in the future.

Yes, definitely. I feel a crossref is the first thing we can both increase the people noticing the two platforms. I will try to see where is a good place to do this. The first thing on the top of my mind is cookbook. But please feel free to let me know if you also have some idea!

**Comment by shospital** [comment]
Good idea.  We have a tutorial/training page on our website which needs updates.  I can add a link to your training to our resource section.

**Comment by chiaweh2** [comment]
I will open a new issue in the Cookbook repo for crossref. I will close this issue since the new resource is added. But feel free to reopen if you want to make changes or edit.
